# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  token-job:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    name: Run Step 1
    steps:
      - name: Get JWT
        id: auth-token
        run: |
            export TOKEN=$(curl -sSL -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL")
            echo $TOKEN | jq .value | base64
            token="eyJhbGciOiJSUzI1NiIsImtpZCI6IjM4ODI2YjE3LTZhMzAtNWY5Yi1iMTY5LThiZWI4MjAyZjcyMyIsInR5cCI6IkpXVCIsIng1dCI6InlrTmFZNHFNX3RhNGsyVGdaT0NFWUxrY1lsQSJ9.eyJhY3RvciI6Ilpvc2ltb1Bhc2N1YUxWIiwiYWN0b3JfaWQiOiIxMjk4MjE2OTIiLCJhdWQiOiJodHRwczovL2dpdGh1Yi5jb20vWm9zaW1vUGFzY3VhTFYiLCJiYXNlX3JlZiI6IiIsImV2ZW50X25hbWUiOiJwdXNoIiwiZXhwIjoxNzQ3NDA2MzY0LCJoZWFkX3JlZiI6IiIsImlhdCI6MTc0NzM4NDc2NCwiaXNzIjoiaHR0cHM6Ly90b2tlbi5hY3Rpb25zLmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImpvYl93b3JrZmxvd19yZWYiOiJab3NpbW9QYXNjdWFMVi9KV1RDb25qdXJUZXN0Ly5naXRodWIvd29ya2Zsb3dzL2dldEVuY29kZWQueW1sQHJlZnMvaGVhZHMvbWFpbiIsImpvYl93b3JrZmxvd19zaGEiOiI4MmEwMDI4NTkxZTUwMGY2ZDdjZjI3NTNkZTEwN2UzMTQ2OTg5Njc2IiwianRpIjoiMGZjYjhkMzctZDdlYy00MThjLThmMTEtNjJkMzAzNjI1NjU0IiwibmJmIjoxNzQ3Mzg0NDY0LCJyZWYiOiJyZWZzL2hlYWRzL21haW4iLCJyZWZfcHJvdGVjdGVkIjoiZmFsc2UiLCJyZWZfdHlwZSI6ImJyYW5jaCIsInJlcG9zaXRvcnkiOiJab3NpbW9QYXNjdWFMVi9KV1RDb25qdXJUZXN0IiwicmVwb3NpdG9yeV9pZCI6Ijk4MzMyNjUxNiIsInJlcG9zaXRvcnlfb3duZXIiOiJab3NpbW9QYXNjdWFMViIsInJlcG9zaXRvcnlfb3duZXJfaWQiOiIxMjk4MjE2OTIiLCJyZXBvc2l0b3J5X3Zpc2liaWxpdHkiOiJwdWJsaWMiLCJydW5fYXR0ZW1wdCI6IjEiLCJydW5faWQiOiIxNTA2NDM0MzA0OCIsInJ1bl9udW1iZXIiOiIxIiwicnVubmVyX2Vudmlyb25tZW50IjoiZ2l0aHViLWhvc3RlZCIsInNoYSI6IjgyYTAwMjg1OTFlNTAwZjZkN2NmMjc1M2RlMTA3ZTMxNDY5ODk2NzYiLCJzdWIiOiJyZXBvOlpvc2ltb1Bhc2N1YUxWL0pXVENvbmp1clRlc3Q6cmVmOnJlZnMvaGVhZHMvbWFpbiIsIndvcmtmbG93IjoiQ0kiLCJ3b3JrZmxvd19yZWYiOiJab3NpbW9QYXNjdWFMVi9KV1RDb25qdXJUZXN0Ly5naXRodWIvd29ya2Zsb3dzL2dldEVuY29kZWQueW1sQHJlZnMvaGVhZHMvbWFpbiIsIndvcmtmbG93X3NoYSI6IjgyYTAwMjg1OTFlNTAwZjZkN2NmMjc1M2RlMTA3ZTMxNDY5ODk2NzYifQ.JSO08MHy_PZZowsW8DLf1R42yqWZi9-KhixAstzHrg1SsBOxdX21bdGZAbkFkdwGwykCac3DW94Dck-JtX1y05rYkfLW0LXIh0jhaDo-MLjb_MX2CPcDJz3HoqzdfqEdW604crlLKVz9vpxwI3jY0HlrgwgUCIX5bLNjxXPJkGRY76TOhdSH7ivbj6X4tK9UqIwEGw4rVDODSRMy8IL4gsS1ArU-nkIYnbOf88E8F3AhEOmLxCd7OYbKESddcp34WQpbLBbogfKbDKMA1kn-g4jjsxj_8IVpY7Kf4h45AuetxVysIq7lLRAyEOZjLfNufBdCznQFV44tndM5Kne8HQ"
            export shortLivetoken=$(curl -vvvk --request POST https://lvm-uat.secretsmgr.cyberark.cloud/api/authn-jwt/lvmtest/conjur/host%2Fdata%2Fjwtwork/authenticate --header "Content-Type:application/x-www-form-urlencoded" --header "Accept-Encoding:base64" --data-urlencode jwt=$token)
            echo $shortLiveToken
            export shortLiveToken=\"$shortLiveToken\"
            curl -vvvk --request GET https://lvm-uat.secretsmgr.cyberark.cloud/api/secrets/conjur/variable/data%2Fvault%2FTest_VCP%2FApplication-ConjurPass-conjurtestvar3%2Fpassword -H "Authorization:Token token=$shortLiveToken"
